version: '3.7'

services:
  your-database-name:
    image: postgres:13
    container_name: your-database-name
    restart: unless-stopped
    environment:
      - POSTGRES_USER=your-username
      - POSTGRES_PASSWORD=your-password
      - POSTGRES_DB=your-database-name
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
